# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoLMatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoLMatch

  pod 'Moya', '~> 11.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Nuke', '~> 7.4.2'

  # logger
  pod 'XCGLogger', '~> 6.1.0'

  target 'LoLMatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoLMatchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
